name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create a local Kubernetes cluster
      uses: engineerd/setup-kind@v0.5.0

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Install
      run: go install -v ./...

    - name: Run integration tests
      run: go test --tags=integration ./...
