name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: KinD (Kubernetes in Docker) Action
      uses: engineerd/setup-kind@v0.5.0

    - name: Run Integration Tests
      run: |
        kubectl cluster-info
        echo "current-context:" $(kubectl config current-context)
        echo "environment-kubeconfig:" ${KUBECONFIG}
